### ISSUE TITLE
APEX 18.x badges

### ISSUE THREAD

**Issue by rimblas** [Dani3lSun/apex-github-badges#2]
Looks like we could use badges for APEX 18.1 & 18.2

Maybe someone with svg knowledge can contribute.

**Comment by Dani3lSun** [comment]
Just added them, fyi you could always create your own with the shields.io web service, see:
https://github.com/Dani3lSun/apex-github-badges#create-your-own-badge

**Comment by rimblas** [comment]
Ha! I used to know that.  I should have read the whole README.
Here I was editing the svg files in the fork, I was about to do a PR.  It was a nice exercise.
Thank you!
